# Data Analysis

In [26]:
## Dependencies
import yfinance as yf
import pandas as pd
import numpy as np

### 1. Acquiring datasets

In [ ]:
# NVIDIA dataset:
nvidia = yf.download("NVDA", start="2020-01-01", end="2026-07-01")
nvidia.columns = nvidia.columns.get_level_values(0)
nvidia.columns.name = None # removing title of column names.
nvidia.reset_index(inplace=True) # resetting index to have date as a column.

nvidia["Date"] = pd.to_datetime(nvidia["Date"]).dt.strftime("%Y-%m-%d") # date column as Date.
nvidia.head(5)

[*********************100%***********************]  1 of 1 completed

        Date     Close      High       Low      Open     Volume
0 2020-01-02  5.963803  5.963803  5.884505  5.934968  237536000
1 2020-01-03  5.868349  5.912100  5.819377  5.844236  205384000
2 2020-01-06  5.892956  5.898177  5.749026  5.775127  262636000
3 2020-01-07  5.964300  6.010039  5.876301  5.921294  314856000
4 2020-01-08  5.975487  6.016752  5.920053  5.960075  277108000

In [63]:
# Semiconductor billing dataset:
sia = pd.read_csv('americas_semiconductor_billings.csv') # one value per month; low granularity compared to nvidia dataset.
sia["Date"] = pd.to_datetime(sia["Date"]).dt.strftime("%Y-%m-%d")
sia.head(5)

/var/folders/7n/53byrv256zx1_3t79kv_fj880000gn/T/ipykernel_45893/3164548754.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  sia["Date"] = pd.to_datetime(sia["Date"]).dt.strftime("%Y-%m-%d")

         Date   Value
0  2026-05-31  46.42M
1  2026-04-30  41.53M
2  2026-03-31  40.60M
3  2026-02-28  36.20M
4  2026-01-31  24.63M

In [90]:
# Merging:
merged = pd.merge(
    nvidia,
    sia[["Date", "Value"]],
    on="Date",
    how="left" # keep the all dates form nvidia set.
)

merged["Value"] = merged["Value"].fillna("")

## Output:
display(merged[merged["Value"] != ""].head(5)) # value column filled only at end of month.
display(merged.head(10))

           Date      Close       High        Low       Open     Volume   Value
607  2022-05-31  18.616369  19.142796  18.295328  18.923450  664100000  12.61M
628  2022-06-30  15.117032  15.523902  14.820854  15.318472  686070000  12.10M
671  2022-08-31  15.052212  15.496977  14.917585  15.341409  573710000  11.52M
692  2022-09-30  12.108989  12.601768  12.045147  12.057117  565638000  13.77M
713  2022-10-31  13.463630  13.803787  13.264124  13.743935  486341000  11.69M

         Date     Close      High       Low      Open     Volume Value
0  2020-01-02  5.963803  5.963803  5.884505  5.934968  237536000
1  2020-01-03  5.868349  5.912100  5.819377  5.844236  205384000
2  2020-01-06  5.892956  5.898177  5.749026  5.775127  262636000
3  2020-01-07  5.964300  6.010039  5.876301  5.921294  314856000
4  2020-01-08  5.975487  6.016752  5.920053  5.960075  277108000
5  2020-01-09  6.041115  6.113453  5.987421  6.061747  255112000
6  2020-01-10  6.073429  6.178581  6.059260  6.148253  316296000
7  2020-01-13  6.263845  6.288952  6.133835  6.156457  319840000
8  2020-01-14  6.147011  6.246445  6.133835  6.221089  359088000
9  2020-01-15  6.104503  6.182062  6.078650  6.159689  263104000